# Generated by Django 2.1.15 on 2021-12-27 21:05

import db_models.hangman.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('common', '0001_initial'),
        ('hangman', '0002_auto_20211223_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanBattleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('user1_guesses', models.CharField(default='', max_length=26, validators=[db_models.hangman.models.validate_lower_case])),
                ('user2_guesses', models.CharField(default='', max_length=26, validators=[db_models.hangman.models.validate_lower_case])),
                ('user1_draw_guesses', models.CharField(default='', max_length=20, validators=[db_models.hangman.models.validate_lower_case])),
                ('user2_draw_guesses', models.CharField(default='', max_length=20, validators=[db_models.hangman.models.validate_lower_case])),
                ('result', models.SmallIntegerField(choices=[(1, 'PLAYING'), (2, 'PLAYER_1_WIN'), (3, 'PLAYER_2_WIN'), (4, 'DRAW')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hangman_battles1', to='common.User')),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hangman_battles2', to='common.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hangman_battles', to='words.EnglishWord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HangmanBattleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.BigIntegerField()),
                ('state', models.SmallIntegerField(choices=[(1, 'FIRST_PLAYER_TURN'), (2, 'SECOND_PLAYER_TURN'), (3, 'TIE_BREAKER')], default=1)),
                ('user1_wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('user2_wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('last_interaction_timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hangman_battle_session', to='hangman.HangmanBattleGame')),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hangman_session1', to='common.User')),
                ('user2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hangman_session2', to='common.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
