# Generated by Django 2.1.15 on 2021-12-22 00:36

from django.db import migrations, models


def fill_words(apps, schema_editor):
    EnglishWord = apps.get_model("words", "EnglishWord")
    with open('data/hangman_words.txt') as f:
        words = [EnglishWord(word=word.strip()) for word in f.readlines()]
    EnglishWord.objects.bulk_create(words)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmoji',
            fields=[
                ('letter', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('times_used', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(fill_words),
    ]
