# Generated by Django 2.1.15 on 2022-01-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('permission_level', models.IntegerField(default=0)),
                ('task', models.PositiveSmallIntegerField()),
                ('arg0', models.TextField(default='')),
                ('arg1', models.TextField(default='')),
                ('arg2', models.TextField(default='')),
                ('arg3', models.TextField(default='')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_commands', to='common.Guild')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
