# Generated by Django 2.1.15 on 2022-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_command_action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcommand',
            name='arg4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customcommand',
            name='arg5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customcommand',
            name='arg6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customcommand',
            name='arg7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customcommand',
            name='arg8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customcommand',
            name='arg9',
            field=models.TextField(default=''),
        ),
    ]
